/*
 * Administrative things for libfaim.
 *
 *  
 */

#include <faim/aim.h>
#include <aim_buildcode.h> /* generated by mkbuildinfo.sh */

char *aim_getbuilddate(void)
{
  return AIM_BUILDDATE;
}

char *aim_getbuildtime(void)
{
  return AIM_BUILDTIME;
}

char *aim_getbuildstring(void)
{
  static char string[100];

  snprintf(string, 99, "%d.%d.%d-%s%s", 
	   FAIM_VERSION_MAJOR,
	   FAIM_VERSION_MINOR,
	   FAIM_VERSION_MINORMINOR,
	   aim_getbuilddate(),
	   aim_getbuildtime());
  return string;
}

