
CFLAGS = -Wstrict-prototypes -Wall -I. -g 

ifdef LIBFAIM_INC
CFLAGS += -I$(LIBFAIM_INC)
endif

LDFLAGS = 
ifdef LIBFAIM_LIB
LDFLAGS += -lfaim -L$(LIBFAIM_LIB)
endif

ifdef SOLARIS
CC = gcc
MAKE = gmake
endif

AR = ar
RANLIB = ranlib

